{{- if or .Values.apiserver.enableMutatingWebhook .Values.apiserver.enableValidatingWebhook }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "petset.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petset.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: webhook-server
    {{- include "petset.selectorLabels" . | nindent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
{{ end }}
