apiVersion: v2
description: PgOutbox by AppsCode
name: pgoutbox
version: v2025.4.30
appVersion: v0.0.2
kubeVersion: ">=1.28.0"
annotations:
  charts.openshift.io/name: pgoutbox
home: https://kubedb.com/
icon: https://cdn.appscode.com/images/products/stash/petset-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
