{{- if .Values.kubeconfigSecretName }}
{{ range $path, $data := .Files.Glob  "crds/**.yaml" }}

{{ $content := toString $data }}
{{ $crd := dig "spec" "names" "plural" "" ($content | fromYaml) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-ui-server.fullname" $ }}-regcrd-{{ $crd }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  crd.yaml: |
    {{- $content | nindent 4 }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-ui-server.fullname" $ }}-regcrd-{{ $crd }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      {{- include "appscode.imagePullSecrets" $ | nindent 6 }}
      automountServiceAccountToken: false
      containers:
      - name: kubectl
        image: {{ include "image.registry" $ }}/kubectl:1.23
        workingDir: /var/run/secrets/ocm
        command:
          - sh
          - -c
          - "sleep 2; \
            kubectl --kubeconfig=auth/kubeconfig apply -f /etc/crds/crd.yaml; \
            "
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        volumeMounts:
        - mountPath: /var/run/secrets/ocm/auth
          name: ocm-auth
        - name: crd-volume
          mountPath: /etc/crds
      volumes:
      - name: ocm-auth
        secret:
          defaultMode: 420
          secretName: {{ $.Values.kubeconfigSecretName }}
      - name: crd-volume
        configMap:
          name: {{ include "kube-ui-server.fullname" $ }}-regcrd-{{ $crd }}
      restartPolicy: Never
{{- end }}
{{- end }}
