# https://github.com/helm/charts/blob/master/test/README.md#providing-custom-test-values
operator:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
rbacproxy:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
cleaner:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
