project:
  name: Kubernetes UI Server by AppsCode
  shortName: Kubernetes UI Server
  url: https://github.com/kubeops/ui-server
  description: Kubernetes UI Server for ByteBuilders
  app: a Kubernetes UI Server
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kube-ui-server
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.16+
release:
  name: kube-ui-server
  namespace: kubeops
