apiVersion: v2
name: cert-manager-crds
description: Jetstack cert-manager CRDs
type: application
version: 1.9.1
appVersion: v1.9.1
home: https://cert-manager.io
icon: https://cdn.appscode.com/images/products/appscode/appscode-512x512.png
sources:
- https://github.com/jetstack/cert-manager
maintainers:
- name: appscode
  email: support@appscode.com
