apiVersion: v2
description: Kubernetes Panopticon by AppsCode
name: panopticon
version: v2024.11.8
appVersion: v0.0.17
home: https://github.com/kubeops/panopticon
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/panopticon
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: ace-user-roles
  repository: oci://ghcr.io/appscode-charts
  condition: ace-user-roles.enabled
  version: v2024.9.30
