apiVersion: v2
description: Kubernetes Panopticon by AppsCode
name: panopticon
version: v2026.1.15
appVersion: v0.0.21
kubeVersion: ">=1.28.0"
annotations:
  charts.openshift.io/name: panopticon
home: https://github.com/kubeops/panopticon
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/panopticon
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: ace-user-roles
  repository: file://../ace-user-roles
  condition: ace-user-roles.enabled
  version: v2025.3.14
