apiVersion: v2
name: external-dns-operator
description: A Helm chart for External DNS Operator by AppsCode
type: application
version: v2026.1.15
appVersion: v0.3.0
kubeVersion: ">=1.28.0-0"
annotations:
  charts.openshift.io/name: external-dns-operator
home: https://github.com/kubeops/external-dns-operator
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/external-dns-operator
maintainers:
- name: appscode
  email: support@appscode.com
