project:
  name: External DNS Operator by AppsCode
  shortName: External DNS Operator
  url: https://github.com/kubeops/external-dns-operator
  description: External DNS Operator for Kubernetes
  app: an External DNS Operator
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: external-dns-operator
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.16+
release:
  name: external-dns-operator
  namespace: kubeops
