apiVersion: v2
name: cert-manager-csi-driver-cacerts
description: A Helm chart for cert-manager-csi-driver-cacerts
type: application
version: v2026.1.15
appVersion: v0.5.0
kubeVersion: ">=1.28.0-0"
annotations:
  charts.openshift.io/name: cert-manager-csi-driver-cacerts
home: https://github.com/kubeops/csi-driver-cacerts
icon: https://cdn.appscode.com/images/products/kubed/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/csi-driver-cacerts
maintainers:
- name: appscode
  email: support@appscode.com
