apiVersion: v2
name: supervisor
description: A Helm chart for Supervisor by AppsCode
type: application
version: v2023.03.23
appVersion: v0.0.3
home: https://github.com/kubeops/supervisor
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/supervisor
maintainers:
- name: appscode
  email: support@appscode.com
