apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "statefulset.labels" . | nindent 4 }}
  {{- if eq .Values.monitoring.agent "prometheus.io/builtin" }}
  annotations:
    prometheus.io/scrape: "true"
    {{- if .Values.monitoring.operator }}
    prometheus.io/operator_path: "/metrics"
    prometheus.io/operator_port: "8443"
    prometheus.io/operator_scheme: "https"
    {{- end }}
  {{- end }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "statefulset.selectorLabels" . | nindent 4 }}
