apiVersion: v2
name: fargocd
description: A Helm chart for FluxCD to ArgoCD Bridge
type: application
version: v2026.1.15
appVersion: v0.0.2
kubeVersion: ">=1.28.0-0"
annotations:
  charts.openshift.io/name: fargocd
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
