apiVersion: v2
name: kmodules-crds
description: Shared Kubernetes Custom Resource Definitions for AppsCode Projects
type: application
version: v0.25.1
appVersion: v0.25.1
home: https://appscode.com
icon: https://cdn.appscode.com/images/products/appscode/appscode-512x512.png
sources:
- https://github.com/kmodules/installer
maintainers:
- name: appscode
  email: support@appscode.com
