apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ace-info-reader
  namespace: kube-public
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["ace-info"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ace-info-reader
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ace-info-reader
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
