apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeops:ui:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - auditor.appscode.com
  resources:
  - siteinfos
  verbs: ["create"]
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - whoamis
  verbs: ["create"]
- apiGroups:
  - core.k8s.appscode.com
  resources:
  - genericresources
  - genericresourceservices
  - podviews
  - resourcesummaries
  verbs: ["get", "list"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - renders
  - renderapis
  - rendermenus
  - resourcegraphs
  verbs: ["create"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - resourcedescriptors
  - resourceblockdefinitions
  - resourcelayouts
  - resourceoutlines
  - resourcetabledefinitions
  - menus
  verbs: ["get", "list"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - menus/available
  verbs: ["get"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - usermenus
  verbs: ["*"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - usermenus/available
  verbs: ["get"]
