{{- $auditorPolicy := .Values.policy }}
{{- if not $auditorPolicy }}
{{- $auditorPolicy = `apiVersion: auditor.kubeops.tools/v1alpha1
kind: AuditRegistration
resources:
- group: apps
  resources:
  - deployments
- group: ""
  resources:
  - pods
  - namespaces
  - secrets
- group: appcatalog.appscode.com
  resources:
  - appbindings
- group: catalog.kubedb.com
  resources:
  - etcdversions
  - mysqlversions
  - redisversions
  - mongodbversions
  - postgresversions
  - memcachedversions
  - elasticsearchversions
- group: cloud.bytebuilders.dev
  resources:
  - credentials
  - machinetypes
  - cloudproviders
  - clusterinfos
  - clusteruserauths
  - clusterauthinfotemplates
- group: kubedb.com
  resources:
  - etcds
  - mysqls
  - redises
  - mongodbs
  - snapshots
  - memcacheds
  - postgreses
  - elasticsearches
  - dormantdatabases
- group: kubepack.com
  resources:
  - plans
  - products
- group: monitoring.appscode.com
  resources:
  - incidents
  - podalerts
  - nodealerts
  - clusteralerts
  - searchlightplugins
- group: stash.appscode.com
  resources:
  - tasks
  - restics
  - functions
  - recoveries
  - repositories
  - backupbatches
  - backupsessions
  - restoresessions
  - backupblueprints
  - backupconfigurations
- group: voyager.appscode.com
  resources:
  - ingresses
  - certificates` }}
{{- end}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditor.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
type: Opaque
data:
  "default.yaml": {{ $auditorPolicy | b64enc }}
