apiVersion: v1
kind: Service
metadata:
  name: {{ include "auditor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
{{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  selector:
    {{- include "auditor.selectorLabels" . | nindent 4 }}
