properties:
  enableClusterRoles:
    properties:
      ace:
        type: boolean
      appcatalog:
        type: boolean
      catalog:
        type: boolean
      cert-manager:
        type: boolean
      kubedb:
        type: boolean
      kubedb-ui:
        type: boolean
      kubestash:
        type: boolean
      kubevault:
        type: boolean
      license-proxyserver:
        type: boolean
      metrics:
        type: boolean
      prometheus:
        type: boolean
      stash:
        type: boolean
    required:
    - ace
    - appcatalog
    - catalog
    - cert-manager
    - kubedb
    - kubedb-ui
    - kubestash
    - kubevault
    - license-proxyserver
    - metrics
    - prometheus
    - stash
    type: object
  fullnameOverride:
    type: string
  nameOverride:
    type: string
required:
- enableClusterRoles
type: object
